-- Schema portable generado por introspeccion desde Postgres de Supabase.
-- Sin RLS, sin roles/GRANTs especificos de Supabase (authenticated/anon/service_role).
-- Pensado para un Postgres self-hosted donde el unico cliente de la base es el backend Express.
-- Generado: 2026-08-06T22:58:03.002Z

BEGIN;

-- Tabla: clasificacion
CREATE TABLE "clasificacion" (
  "id_clasificacion" smallint NOT NULL,
  "clasificacion" varchar(50),
  "estatus" smallint DEFAULT 1 NOT NULL
);
ALTER TABLE "clasificacion" ADD CONSTRAINT "clasificacion_pkey" PRIMARY KEY ("id_clasificacion");

-- Tabla: ctas_contables
CREATE TABLE "ctas_contables" (
  "id_ctacontable" smallint NOT NULL,
  "cta_contable" varchar(50),
  "descripcion" text,
  "id_clasificacion_cta" smallint,
  "estatus" smallint DEFAULT 1 NOT NULL
);
ALTER TABLE "ctas_contables" ADD CONSTRAINT "ctas_contables_pkey" PRIMARY KEY ("id_ctacontable");

-- Tabla: activos
CREATE TABLE "activos" (
  "id_consecutivo" smallint NOT NULL,
  "numero_inventario" varchar(50),
  "descripcion" text,
  "marca" varchar(50),
  "modelo" varchar(50),
  "numero_serie" varchar(50),
  "f_factura" timestamp with time zone,
  "f_alta" timestamp with time zone,
  "costo" numeric(14,2),
  "folio_factura" varchar(20),
  "observaciones" text,
  "estatus" smallint,
  "clasificacion" smallint,
  "ultimo_nomina" varchar(50),
  "id_cta_contable" smallint,
  "tipo" smallint
);
ALTER TABLE "activos" ADD CONSTRAINT "activos_pkey" PRIMARY KEY ("id_consecutivo");

-- Tabla: audit_logs
CREATE TABLE "audit_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tabla" varchar(100) NOT NULL,
  "registro_id" varchar(100) NOT NULL,
  "accion" varchar(20) NOT NULL,
  "campo" varchar(100),
  "valor_anterior" text,
  "valor_nuevo" text,
  "id_usuario" integer NOT NULL,
  "usuario" varchar(100) NOT NULL,
  "nombre_usuario" varchar(255),
  "ip_address" varchar(50),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id");

-- Tabla: auth_login_attempts
CREATE TABLE "auth_login_attempts" (
  "identifier" text NOT NULL,
  "attempts" integer DEFAULT 0 NOT NULL,
  "first_attempt_at" timestamp with time zone DEFAULT now() NOT NULL,
  "locked_until" timestamp with time zone
);
ALTER TABLE "auth_login_attempts" ADD CONSTRAINT "auth_login_attempts_pkey" PRIMARY KEY ("identifier");

-- Tabla: tipos_inmueble
CREATE TABLE "tipos_inmueble" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text
);
ALTER TABLE "tipos_inmueble" ADD CONSTRAINT "tipos_inmueble_pkey" PRIMARY KEY ("id");

-- Tabla: bienes_inmuebles
CREATE TABLE "bienes_inmuebles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "numero_inventario" varchar(50) NOT NULL,
  "nombre" varchar(200),
  "descripcion" text,
  "id_tipo_inmueble" integer,
  "direccion" text NOT NULL,
  "colonia" varchar(100),
  "codigo_postal" varchar(10),
  "municipio" varchar(100) DEFAULT 'San Juan del Río'::character varying,
  "estado" varchar(100) DEFAULT 'Querétaro'::character varying,
  "latitud" numeric(10,8),
  "longitud" numeric(11,8),
  "superficie_terreno" numeric(12,2),
  "superficie_construccion" numeric(12,2),
  "niveles" smallint,
  "uso_actual" varchar(100),
  "numero_escritura" varchar(50),
  "fecha_escritura" date,
  "notaria" varchar(200),
  "volumen_libro" varchar(50),
  "folio_registro" varchar(50),
  "clave_catastral" varchar(50),
  "valor_catastral" numeric(14,2),
  "valor_comercial" numeric(14,2),
  "costo_adquisicion" numeric(14,2),
  "fecha_adquisicion" date,
  "id_cta_contable" smallint,
  "responsable_nomina" varchar(20),
  "estatus" smallint DEFAULT 1,
  "observaciones" text,
  "fecha_registro" timestamp with time zone DEFAULT now(),
  "fecha_modificacion" timestamp with time zone DEFAULT now(),
  "escritura_url" text
);
ALTER TABLE "bienes_inmuebles" ADD CONSTRAINT "bienes_inmuebles_numero_inventario_key" UNIQUE ("numero_inventario");
ALTER TABLE "bienes_inmuebles" ADD CONSTRAINT "bienes_inmuebles_pkey" PRIMARY KEY ("id");

-- Tabla: consignas
CREATE TABLE "consignas" (
  "id_consigna" smallint NOT NULL,
  "consigna" varchar(50),
  "estatus" smallint DEFAULT 1 NOT NULL
);
ALTER TABLE "consignas" ADD CONSTRAINT "consignas_pkey" PRIMARY KEY ("id_consigna");

-- Tabla: empleados
CREATE TABLE "empleados" (
  "nomina" text NOT NULL,
  "nombre" text NOT NULL,
  "departamento" text,
  "puesto" text,
  "activo" text DEFAULT 'A'::text NOT NULL
);
ALTER TABLE "empleados" ADD CONSTRAINT "empleados_pkey" PRIMARY KEY ("nomina");

-- Tabla: modulos
CREATE TABLE "modulos" (
  "id_modulo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "clave" varchar(50) NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "grupo" varchar(50) NOT NULL,
  "orden" smallint DEFAULT 0 NOT NULL
);
ALTER TABLE "modulos" ADD CONSTRAINT "modulos_clave_key" UNIQUE ("clave");
ALTER TABLE "modulos" ADD CONSTRAINT "modulos_pkey" PRIMARY KEY ("id_modulo");

-- Tabla: resguardos
CREATE TABLE "resguardos" (
  "id_resguardo" smallint NOT NULL,
  "folio" varchar(20),
  "numero_inventario" varchar(50) NOT NULL,
  "nomina" varchar(60),
  "estatus" boolean,
  "id_usuario" smallint,
  "fecha" timestamp with time zone
);
ALTER TABLE "resguardos" ADD CONSTRAINT "resguardos_pkey" PRIMARY KEY ("id_resguardo");

-- Tabla: revision_sesiones
CREATE TABLE "revision_sesiones" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "id_usuario" smallint NOT NULL,
  "mode" varchar(50) DEFAULT 'responsable'::character varying NOT NULL,
  "responsable_id" varchar(255),
  "responsable_nombre" varchar(500),
  "responsable_tipo" varchar(50),
  "expected" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "scans" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "notes" text,
  "estatus" varchar(20) DEFAULT 'activa'::character varying NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "revision_sesiones" ADD CONSTRAINT "revision_sesiones_pkey" PRIMARY KEY ("id");

-- Tabla: usuarios
CREATE TABLE "usuarios" (
  "id_usuario" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre" varchar(50),
  "usuario" varchar(50),
  "password" varchar(15),
  "password_hash" varchar(200),
  "permisos" smallint
);
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id_usuario");
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_usuario_key" UNIQUE ("usuario");

-- Tabla: usuario_modulos
CREATE TABLE "usuario_modulos" (
  "id_usuario" integer NOT NULL,
  "id_modulo" integer NOT NULL,
  "puede_ver" boolean DEFAULT true NOT NULL,
  "puede_editar" boolean DEFAULT false NOT NULL
);
ALTER TABLE "usuario_modulos" ADD CONSTRAINT "usuario_modulos_pkey" PRIMARY KEY ("id_usuario", "id_modulo");

-- Foreign keys (al final, ya con todas las tablas creadas)
ALTER TABLE "activos" ADD CONSTRAINT "fk_activos_clasificacion" FOREIGN KEY ("clasificacion") REFERENCES "clasificacion" ("id_clasificacion");
ALTER TABLE "activos" ADD CONSTRAINT "fk_activos_cta_contable" FOREIGN KEY ("id_cta_contable") REFERENCES "ctas_contables" ("id_ctacontable");
ALTER TABLE "bienes_inmuebles" ADD CONSTRAINT "bienes_inmuebles_id_cta_contable_fkey" FOREIGN KEY ("id_cta_contable") REFERENCES "ctas_contables" ("id_ctacontable");
ALTER TABLE "bienes_inmuebles" ADD CONSTRAINT "bienes_inmuebles_id_tipo_inmueble_fkey" FOREIGN KEY ("id_tipo_inmueble") REFERENCES "tipos_inmueble" ("id");
ALTER TABLE "usuario_modulos" ADD CONSTRAINT "usuario_modulos_id_modulo_fkey" FOREIGN KEY ("id_modulo") REFERENCES "modulos" ("id_modulo");
ALTER TABLE "usuario_modulos" ADD CONSTRAINT "usuario_modulos_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario");

-- Indices adicionales (no derivados de PK/UNIQUE)
CREATE INDEX idx_consignas_estatus ON consignas USING btree (estatus);
CREATE INDEX idx_clasificacion_estatus ON clasificacion USING btree (estatus);
CREATE INDEX idx_ctas_contables_estatus ON ctas_contables USING btree (estatus);
CREATE INDEX idx_audit_logs_tabla_registro ON audit_logs USING btree (tabla, registro_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs USING btree (created_at DESC);
CREATE INDEX idx_audit_logs_usuario ON audit_logs USING btree (id_usuario);
CREATE INDEX idx_inmuebles_inventario ON bienes_inmuebles USING btree (numero_inventario);
CREATE INDEX idx_inmuebles_direccion ON bienes_inmuebles USING btree (direccion);
CREATE INDEX idx_inmuebles_tipo ON bienes_inmuebles USING btree (id_tipo_inmueble);
CREATE INDEX idx_inmuebles_estatus ON bienes_inmuebles USING btree (estatus);
CREATE INDEX idx_revision_sesiones_usuario_estatus ON revision_sesiones USING btree (id_usuario, estatus);
CREATE INDEX idx_usuario_modulos_usuario ON usuario_modulos USING btree (id_usuario);
CREATE INDEX ix_res_inv_fecha ON resguardos USING btree (numero_inventario, fecha DESC);
CREATE INDEX ix_res_folio ON resguardos USING btree (folio);
CREATE INDEX ix_res_nomina ON resguardos USING btree (nomina);

COMMIT;
