-- Prepara `consignas` (instituciones) para tener CRUD desde la app:
--
-- 1) id_consigna no tenía generación automática (ni serial ni identity),
--    así que crear una institución requería calcular el siguiente id a mano
--    en el cliente (riesgo de condición de carrera). Se agrega identity
--    partiendo del máximo id actual, sin afectar los ids ya existentes.
--
-- 2) La tabla solo tenía policy de SELECT ("Allow read consignas"); no había
--    ninguna policy de escritura, así que insert/update/delete quedaban
--    bloqueados para todos (mismo patrón que el bug ya visto en
--    empleados — ver 20260804150000_empleados_rls_fix.sql).

alter table public.consignas
  alter column id_consigna add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.consignas', 'id_consigna'),
  greatest((select coalesce(max(id_consigna), 0) from public.consignas), 1)
);

drop policy if exists "Escritura autenticada consignas" on public.consignas;
create policy "Escritura autenticada consignas" on public.consignas
  for all to anon, authenticated using (true) with check (true);
